services:
  api:
    build: .
    container_name: api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
     
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - api
volumes:
  postgres_data:
  api_venv: